# Generated by Django 3.2 on 2022-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_match',
            name='match',
            field=models.ManyToManyField(related_name='_location_match_location_match_match_+', to='location_match.Location_Match'),
        ),
    ]
