# Generated by Django 3.2 on 2022-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('location_match', '0002_alter_location_match_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('liked_by', models.ManyToManyField(to='profiles.UserProfile')),
            ],
        ),
    ]
