# Generated by Django 3.2 on 2022-02-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('location_match', '0003_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='liked_by',
            field=models.ManyToManyField(blank=True, to='profiles.UserProfile'),
        ),
    ]
